import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { LazyLoadImage } from "react-lazy-load-image-component";
import Nav from "../components/Nav";
import Head from "next/head";

function CountryDetail() {
  const [allCountries, setAllCountries] = useState([]);
  const [testing, setTesting] = useState([]);
  const router = useRouter();
  const countryId = router.query.countryId;

  useEffect(() => {
    const getAllCountries = async () => {
      try {
        const res = await fetch("https://restcountries.eu/rest/v2/all");
        const data = await res.json();
        setAllCountries(data);
      } catch (err) {
        console.log(err);
      }
    };

    getAllCountries();
  }, []);

  const __country = allCountries.find((item) => item.name === countryId);

  const languages = __country?.languages?.map((item, i) => (
    <p key={i}>{item.name}, </p>
  ));

  /*ex:["MNE","GRC","MKD","KOS"]  */
  const borderCountries = __country?.borders?.map((item) => item);

  const handleNewCountryClick = (stringId) => {
    const getCountry = allCountries.find(
      (item) => item.alpha3Code === stringId
    );
    /* console.log(getCountry.name); */
    router.replace(`/${getCountry.name}`);
  };

  return (
    <div className="font-mainFont">
      <Head>
        <title>{countryId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="px-5 flex flex-col  items-center h-screen overflow-y-auto pt-28 bg-mainDark text-white">
        <div className="flex flex-col w-full items-center">
          {/* BACK BUTTON */}
          <div className="w-60">
            <button onClick={() => router.push("/")}>Back</button>
          </div>
          {/* Country Flag */}
          <LazyLoadImage
            src={__country?.flag}
            effect=""
            className="rounded-md"
            height={400}
            width={250}
          />
          {/* Country Name */}
          <div className="w-60">
            <h2 className="mt-5 mb-5 font-extrabold text-xl">
              {__country?.name}
            </h2>
            {/* Native name */}
            <p>Native name: {__country?.nativeName}</p>
            {/* Pupulation */}
            <p>Population: {__country?.population}</p>
            {/* Region */}
            <p>Region: {__country?.region}</p>
            {/* Sub Region */}
            <p>Sub Region: {__country?.subregion}</p>
            {/* Capital */}
            <p>Capital: {__country?.capital}</p>
            {/* Top Level Domain */}
            <p>Top Level Domain: {__country?.topLevelDomain}</p>
            {/* Currencies */}
            <p>Currencies: {__country?.currencies[0]?.name}</p>
            {/* Languages */}
            <div className="flex flex-row">
              <p>Languages: </p>
              {languages}
            </div>
            {/* Border Coutnries-> */}
            <p>Border Countries: </p>
            <div className="flex  w-72 overflow-x-auto flex-wrap mb-6">
              {/* buttons for border countries */}
              {__country?.borders?.map((item, i) => (
                <div
                  onClick={() => handleNewCountryClick(item)}
                  key={i}
                  className="mr-3 mt-3 cursor-pointer flex w-14 border-2 border-borderColor flex-col justify-center items-center bg-mainDarkGrayish px-4 py-2"
                >
                  <p className="font-extralight text-gray-400 text-sm">
                    {item}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CountryDetail;
