import Head from "next/head";
import Nav from "../components/Nav";
import React, { useEffect, useState } from "react";
import { SearchIcon } from "@heroicons/react/outline";
import Select from "react-select";
import Image from "next/image";
import Country from "../components/Country";
/* import { LazyLoadImage } from "react-lazy-load-image-component"; */
import Link from "next/link";
import { useRouter } from "next/router";

/* https://www.youtube.com/watch?v=iW39Merz0zE */
const url = "https://restcountries.eu/rest/v2/all";
export async function getServerSideProps() {
  const res = await fetch(url);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  /* console.log("data", data); */
  const router = useRouter();

  const [areaSelected, setAreaSelected] = useState("Select a region");
  /*   const [allCountries, setAllCountries] = useState([]); */

  /* useEffect(() => {
    const getAllCountries = async () => {
      try {
        const res = await fetch("https://restcountries.eu/rest/v2/all");
        const data = await res.json();
        setAllCountries(data);
      } catch (err) {
        console.log(err);
      }
    };

    getAllCountries();
  }, []); */

  return (
    <div className="font-mainFont">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Nav */}
      <Nav />
      {/* MainPage */}
      {/* <MainPage /> */}
      <div className="px-5 flex flex-col  items-center h-screen overflow-y-auto pt-28 bg-mainDark text-white">
        {/* div for (inner)body */}
        <div className="flex flex-col w-full items-center">
          {/* FORM */}
          <form className="flex mb-8 flex-row items-center h-12 w-80 py-6  bg-mainDarkGrayish border-8 border-borderColor rounded-lg">
            <SearchIcon className="h-5 w-5 ml-8 cursor-pointer" />
            <input
              type="text"
              className="font-medium text-sm  w-full flex-grow pl-8 outline-none bg-mainDarkGrayish"
              placeholder="Search for a country..."
            />
          </form>
          {/* FILTER */}
          {/* same w as form container */}
          <div className="w-80 mb-8">
            <select
              value={areaSelected}
              onChange={(e) => setAreaSelected(e.target.value)}
              className=""
            >
              <option value="africa">Africa</option>
              <option value="america">America</option>
              <option value="asia">Asia</option>
              <option value="europe">Europe</option>
              <option value="oceania">Oceania</option>
            </select>
          </div>
          {/* Country Component */}
          {/* flag, name, ...population, region, capital... */}
          {data.map((item, i) => (
            <Country
              key={i}
              flag={item.flag}
              name={item.name}
              population={item.population}
              region={item.region}
              capital={item.capital}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
